name: DigitalOcean CI
env:
  DIGITALOCEAN_REGESTRY : "registry.digitalocean.com/agile-dreamers"
  IMAGE_NAME            : "web-alpine"
  TAG                   : $(echo $GITHUB_SHA | head -c7)
  PATH_TO_KUSTOMIZE     : "website/overlays/dev/kustomization.yaml"
  
on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest    
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.DIGITALOCEAN_REGESTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
    
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200
 
    - name: Push image to DigitalOcean Container Registry
      run: docker push ${{ env.DIGITALOCEAN_REGESTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
      
  update-repo:
    runs-on: ubuntu-latest
    needs: [build]

    steps:   
    - uses: actions/checkout@v3
      with:
        repository: 'Project-Apipuzzle/DigitalOcean-infrastructure'
        ref: main
        token: ${{ secrets.EXTERNAL_REPO_TOKEN }}
        
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install PyYAML
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    - name: Update image tag
      run: python scripts/update_tag.py ${{ env.TAG }} ${{ env.PATH_TO_KUSTOMIZE }}
        
    - name: Commit report
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email '${{ secrets.GIT_USER_EMAIL }}'
        git remote set-url origin https://x-access-token:${{ secrets.EXTERNAL_REPO_TOKEN }}@github.com/Project-Apipuzzle/DigitalOcean-infrastructure
        git commit -am "Tag updated"
        git push